package br.com.fiap.postech.soat.hackathon.service__usuario.domain.model;

import br.com.fiap.postech.soat.hackathon.service__usuario.domain.enums.TipoUsuario;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "Usuario")
@Data
@NoArgsConstructor
public class User {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey  // Gera automaticamente um UUID
    private String id;

    @DynamoDBAttribute(attributeName = "tipoUsuario")
    private TipoUsuario tipoUsuario;

    @DynamoDBAttribute(attributeName = "nome")
    private String nome;

    @DynamoDBAttribute(attributeName = "documento")
    private String documento;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "crm")
    private String crm;

    public User(String id, TipoUsuario tipoUsuario, String nome, String documento, String email, String crm) {
    }
}
