name: Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-session-name: GitHubActionsECR
          role-to-assume: arn:aws:iam::496778154277:role/LabRole

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_URI: 496778154277.dkr.ecr.us-east-1.amazonaws.com/service-usuario
          IMAGE_NAME: service-usuario
        run: |
          docker buildx build --platform linux/amd64 -t $ECR_URI/$IMAGE_NAME:latest .
          docker push $ECR_URI/$IMAGE_NAME:latest

      - name: Post Push Verification
        run: |
          echo "Docker image pushed to ECR: $ECR_URI/$IMAGE_NAME:latest"
